// ════════════════════════════════════════════════════
//  MOTOCULTOR FESTIVAL — DONNÉES DE PROGRAMMATION
// ════════════════════════════════════════════════════

const FESTIVAL_DATA = {
  "2026": {
    dates: {
      thursday:  "2026-08-13",
      friday:    "2026-08-14",
      saturday:  "2026-08-15",
      sunday:    "2026-08-16"
    },
    stages: {
      "Dave Mustage":      { color: "#f97316", cls: "keltia" },
      "Supositor Stage":   { color: "#1a9e8f", cls: "dolmen" },
      "Massey Ferguscène": { color: "#7c4dff", cls: "menhir" },
      "Bruce Dickinscène": { color: "#22c55e", cls: "souterrain" }
    },
    lineup: {
      thursday: [
        { id:'2026-thu-01', name:'Unearth',                     time:'15:15', end:'16:00', stage:'Dave Mustage',      genre:'Metalcore',         country:'🇺🇸 USA',       desc:'Metalcore de Boston taillé comme une lame. Depuis 1998, Unearth allient riffs heavy et mélodies de guitare inoubliables.' },
        { id:'2026-thu-02', name:'Wolfheart',                   time:'16:50', end:'17:50', stage:'Dave Mustage',      genre:'Melodic Death',     country:'🇫🇮 Finlande',  desc:'Melodic death metal finlandais teinté de doom. Wolfheart apporte ses hymnes froids et épiques tout droit venus de l\'hiver nordique.' },
        { id:'2026-thu-03', name:'Kittie',                      time:'18:50', end:'19:50', stage:'Dave Mustage',      genre:'Heavy Metal',       country:'🇨🇦 Canada',    desc:'Reformées après 15 ans d\'absence, les sœurs Morgan et leur groupe iconique de heavy metal féminin reviennent avec une énergie décuplée.' },
        { id:'2026-thu-04', name:'Godsmack',                    time:'20:55', end:'22:05', stage:'Dave Mustage',      genre:'Hard Rock/Metal',   country:'🇺🇸 USA',       desc:'Têtes d\'affiche du jeudi, Godsmack débarquent avec leur hard rock massif et leurs tubes imparables. Sully Erna en frontman charismatique, c\'est une machine à riffs.' },
        { id:'2026-thu-06', name:'200 Stab Wounds',             time:'16:05', end:'16:45', stage:'Supositor Stage',   genre:'Death Metal',       country:'🇺🇸 USA',       desc:'Death metal de Cleveland brutal et sans concession. 200 Stab Wounds incarnent la nouvelle génération du death metal américain avec virulence.' },
        { id:'2026-thu-07', name:'Sanguisugabogg',              time:'17:55', end:'18:45', stage:'Supositor Stage',   genre:'Death Metal',       country:'🇺🇸 USA',       desc:'Death metal grotesque et bestial d\'Ohio. Sanguisugabogg poussent le brutal death dans ses retranchements les plus extrêmes.' },
        { id:'2026-thu-08', name:'Bloodbath',                   time:'19:50', end:'20:50', stage:'Supositor Stage',   genre:'Death Metal',       country:'🇸🇪 Suède',     desc:'Supergroupe du death metal suédois. Bloodbath rendent hommage aux origines de Stockholm avec un son authentiquement old-school et dévastateur.' },
        { id:'2026-thu-09', name:'Death Angel',                 time:'22:10', end:'23:10', stage:'Supositor Stage',   genre:'Thrash Metal',      country:'🇺🇸 USA',       desc:'Thrash metal de Bay Area de légende. Death Angel ont forgé leur réputation à San Francisco dans les années 80 et brûlent encore des scènes entières.' },
        { id:'2026-thu-10', name:'Municipal Waste',             time:'00:30', end:'01:30', stage:'Supositor Stage',   genre:'Crossover Thrash',  country:'🇺🇸 USA',       desc:'Crossover thrash américain fun et dévastateur. Municipal Waste transforme chaque concert en moshpit géant depuis Richmond, Virginia.' },
        { id:'2026-thu-11', name:'Battlesnake',                 time:'16:05', end:'16:45', stage:'Massey Ferguscène', genre:'Heavy Metal',       country:'🇫🇷 France',    desc:'Heavy metal old-school français aux références 80s bien assumées. Battlesnake font rugir la Bretagne avec leurs hymnes de métal pur.' },
        { id:'2026-thu-12', name:'Pilori',                      time:'17:55', end:'18:45', stage:'Massey Ferguscène', genre:'Grindcore/Death',   country:'🇫🇷 France',    desc:'Grindcore et death metal français brutal et engagé. Pilori délivre des messages politiques acérés dans une brutalité musicale totale.' },
        { id:'2026-thu-13', name:'Gaerea',                      time:'19:50', end:'20:50', stage:'Massey Ferguscène', genre:'Black Metal',       country:'🇵🇹 Portugal',  desc:'Black metal masqué portugais de haute intensité dramatique. Performatif, atmosphérique, émotionnellement dévastateur.' },
        { id:'2026-thu-14', name:'Amenra',                      time:'22:10', end:'23:10', stage:'Massey Ferguscène', genre:'Post-Metal/Sludge', country:'🇧🇪 Belgique',  desc:'Post-metal et sludge liturgique belge d\'une intensité mystique rare. Les cérémonies d\'Amenra sur scène dépassent la musique pour toucher au sacré.' },
        { id:'2026-thu-15', name:'Oomph!',                      time:'00:30', end:'01:30', stage:'Massey Ferguscène', genre:'Industrial Metal',  country:'🇩🇪 Allemagne', desc:'Pionniers du Neue Deutsche Härte depuis 1989. Oomph! ont influencé Rammstein et toute la scène industrielle germanique avec leur son unique.' },
        { id:'2026-thu-16', name:'Fauxx',                       time:'15:15', end:'16:00', stage:'Bruce Dickinscène', genre:'Metal/Electro',     country:'🇫🇷 France',    desc:'Projet metal électronique français entre industriel et metal moderne. Fauxx construisent des ambiances dystopiques et hypnotiques.' },
        { id:'2026-thu-17', name:'Brieg Guerveno',              time:'16:50', end:'17:50', stage:'Bruce Dickinscène', genre:'Folk/Rock Breton',  country:'🇫🇷 France',    desc:'Artiste breton ancré dans les traditions musicales de Cornouaille. Brieg Guerveno mêle heritage celtique et modernité avec naturel.' },
        { id:'2026-thu-18', name:'Celkilt x Bagad de Quimper', time:'18:50', end:'19:50', stage:'Bruce Dickinscène', genre:'Folk/Celtic Metal',  country:'🇫🇷 France',    desc:'Rencontre explosive entre Celkilt et le Bagad Ar Meilhoù Glaz de Quimper : cornemuses, bombardes et guitares électriques en terre bretonne.' },
        { id:'2026-thu-19', name:'Denez Prigent',               time:'20:55', end:'22:05', stage:'Bruce Dickinscène', genre:'Folk Breton',       country:'🇫🇷 France',    desc:'Voix majeure de la musique bretonne et mondiale. Denez Prigent transporte ses chants de kan ha diskan dans l\'univers du Motocultor.' },
        { id:'2026-thu-20', name:'Komodrag and the Mounodor',   time:'23:15', end:'00:25', stage:'Bruce Dickinscène', genre:'Stoner/Doom',       country:'🇫🇷 France',    desc:'Stoner doom breton à la personnalité décalée. Komodrag & the Mounodor imposent leur univers avec humour et une lenteur bien sentie.' }
      ],
      friday: [
        { id:'2026-fri-01', name:'Ice Sealed Eyes',              time:'12:45', end:'13:25', stage:'Dave Mustage',      genre:'Black Metal',        country:'🇫🇷 France',    desc:'Black metal atmosphérique français aux textures glaciales. Ice Sealed Eyes créent des paysages sonores hivernaux d\'une grande profondeur.' },
        { id:'2026-fri-02', name:'Cage Fight',                   time:'14:15', end:'14:55', stage:'Dave Mustage',      genre:'Hardcore',           country:'🇬🇧 UK',        desc:'Hardcore britannique direct, court et brutal. Cage Fight distillent une rage punk hardcore sans fioritures ni compromis.' },
        { id:'2026-fri-03', name:'Hellripper',                   time:'15:45', end:'16:30', stage:'Dave Mustage',      genre:'Black/Speed',        country:'🇬🇧 UK',        desc:'Black/speed metal écossais en one-man-band. Hellripper combine vitesse extrême et mélodie noire dans une énergie débordante.' },
        { id:'2026-fri-04', name:'Revnoir',                      time:'17:25', end:'18:10', stage:'Dave Mustage',      genre:'Black/Death',        country:'🇫🇷 France',    desc:'Black death metal français de l\'underground. Revnoir remplace Chelsea Grin et incarnent la violence sonore pure dans des compos sombres et directes.' },
        { id:'2026-fri-05', name:'Lord of the Lost',             time:'19:10', end:'20:00', stage:'Dave Mustage',      genre:'Gothic/Metal',       country:'🇩🇪 Allemagne', desc:'Gothic metal flamboyant de Hambourg, entre dark electro et metal symphonique. Un groupe qui n\'a pas froid aux yeux en termes de spectacle.' },
        { id:'2026-fri-06', name:'Mass Hysteria',                time:'21:00', end:'22:00', stage:'Dave Mustage',      genre:'Metal/Groove',       country:'🇫🇷 France',    desc:'Institution du metal français depuis 1993. Mass Hysteria enchaînent les albums engagés et les concerts incendiaires avec une constance admirable.' },
        { id:'2026-fri-07', name:'Slaughter to Prevail',         time:'23:00', end:'00:10', stage:'Dave Mustage',      genre:'Death Metal/Core',   country:'🇷🇺 Russie',    desc:'Alex Terrible et ses death metal core apocalyptiques. Slaughter to Prevail sont devenus l\'un des groupes les plus imposants de la scène extrême actuelle.' },
        { id:'2026-fri-08', name:'Filth',                        time:'01:20', end:'02:20', stage:'Dave Mustage',      genre:'Grindcore',          country:'🇺🇸 USA',       desc:'Grindcore américain brutal et immédiat. Filth délivrent leur message en rafales de secondes, sans pitié ni pause.' },
        { id:'2026-fri-09', name:'Guineapig',                    time:'13:30', end:'14:10', stage:'Supositor Stage',   genre:'Death Metal',        country:'🇫🇷 France',    desc:'Death metal français direct et sans détour. Guineapig construisent leur set autour de riffs efficaces et d\'une brutalité maîtrisée.' },
        { id:'2026-fri-10', name:'Skaphos',                      time:'15:00', end:'15:40', stage:'Supositor Stage',   genre:'Death Metal',        country:'🇫🇷 France',    desc:'Death metal français au son massif et technique. Skaphos travaillent leur son avec soin pour un résultat brut et impactant.' },
        { id:'2026-fri-11', name:'Bölzer',                       time:'16:35', end:'17:20', stage:'Supositor Stage',   genre:'Black/Death',        country:'🇨🇭 Suisse',    desc:'Duo suisse de black/death metal d\'une intensité magnétique. HzR chante avec une voix qui traverse tout, sur des riffs primitifs et hypnotiques.' },
        { id:'2026-fri-12', name:'Coroner',                      time:'18:15', end:'19:05', stage:'Supositor Stage',   genre:'Thrash/Tech',        country:'🇨🇭 Suisse',    desc:'Retour des légendes du thrash technique suisse. Coroner sont un cas unique : trois musiciens au niveau technique hallucinant pour un son inimitable.' },
        { id:'2026-fri-13', name:'Unleashed',                    time:'20:05', end:'20:55', stage:'Supositor Stage',   genre:'Death Metal',        country:'🇸🇪 Suède',     desc:'Death metal suédois de Stockholm depuis 1989. Unleashed restent fidèles à leurs origines viking et à leur son old-school sans compromis.' },
        { id:'2026-fri-14', name:'Emperor',                      time:'22:05', end:'23:05', stage:'Supositor Stage',   genre:'Symphonic Black',    country:'🇳🇴 Norvège',   desc:'Légendes absolues du black metal symphonique. Emperor en tête d\'affiche, c\'est un événement rare — Ihsahn et Samoth dans toute leur majesté obscure.' },
        { id:'2026-fri-15', name:'Darkened Nocturn Slaughtercult',time:'00:15',end:'01:15', stage:'Supositor Stage',   genre:'Black Metal',        country:'🇩🇪 Allemagne', desc:'Black metal allemand brutal et cérébral d\'une rigueur absolue. DNS n\'existe que pour la scène underground et refuse toute compromission.' },
        { id:'2026-fri-16', name:'Gravity',                      time:'13:30', end:'14:10', stage:'Massey Ferguscène', genre:'Death/Doom',         country:'🇫🇷 France',    desc:'Death doom français aux sonorités caverneuses et aux ambiances oppressantes. Gravity construisent une lourdeur tellurique unique.' },
        { id:'2026-fri-17', name:'Urne',                         time:'15:00', end:'15:40', stage:'Massey Ferguscène', genre:'Doom/Sludge',        country:'🇬🇧 UK',        desc:'Doom sludge britannique dense et atmosphérique. Urne construisent leurs morceaux comme des cathédrales de son, lentement mais sûrement.' },
        { id:'2026-fri-18', name:'Iotunn',                       time:'16:35', end:'17:20', stage:'Massey Ferguscène', genre:'Prog/Doom',          country:'🇩🇰 Danemark',  desc:'Metal progressif et doom épique danois aux claviers de science-fiction et aux compositions labyrinthiques. Un groupe ambitious à découvrir.' },
        { id:'2026-fri-19', name:'Textures',                     time:'18:15', end:'19:05', stage:'Massey Ferguscène', genre:'Prog/Djent',         country:'🇳🇱 Pays-Bas',  desc:'Metal progressif néerlandais à l\'intersection du djent et de la musique expérimentale. Textures ont défriché un territoire sonore unique.' },
        { id:'2026-fri-20', name:'Soen',                         time:'20:05', end:'20:55', stage:'Massey Ferguscène', genre:'Prog Metal',         country:'🇸🇪 Suède',     desc:'Metal progressif atmosphérique réunissant des membres de Tool et Opeth dans l\'esprit. Textures riches et compositions ambitieuses.' },
        { id:'2026-fri-21', name:'Paradise Lost',                time:'22:05', end:'23:05', stage:'Massey Ferguscène', genre:'Gothic Doom',        country:'🇬🇧 UK',        desc:'Pionniers du gothic doom britannique. Plus de 30 ans d\'élégance sombre, de guitares lentes et de mélodies déchirantes.' },
        { id:'2026-fri-22', name:'Alcest',                       time:'00:15', end:'01:15', stage:'Massey Ferguscène', genre:'Post-Black/Shoegaze',country:'🇫🇷 France',    desc:'Neige et son projet Alcest ont inventé le blackgaze. Entre black metal et shoegaze rêveur, leurs albums sont des expériences sonores uniques.' },
        { id:'2026-fri-23', name:'Nawather',                     time:'12:45', end:'13:25', stage:'Bruce Dickinscène', genre:'Metal/Fusion',       country:'🇹🇳 Tunisie',   desc:'Metal fusion tunisien mélangeant musiques orientales et metal occidental. Nawather ouvrent des horizons sonores rares et enrichissants.' },
        { id:'2026-fri-24', name:'Vansind',                      time:'14:15', end:'14:55', stage:'Bruce Dickinscène', genre:'Folk Metal',         country:'🇫🇷 France',    desc:'Folk metal français mêlant instruments traditionnels et metal moderne. Vansind portent une identité régionale avec fierté.' },
        { id:'2026-fri-25', name:'Stille Volk',                  time:'15:45', end:'16:30', stage:'Bruce Dickinscène', genre:'Folk/Pagan',         country:'🇫🇷 France',    desc:'Folk pagan médiéval pyrénéen unique en son genre. Stille Volk convoquent des rituels ancestraux dans des atmosphères forestières et mystiques.' },
        { id:'2026-fri-26', name:'Hrafngrimr',                   time:'17:25', end:'18:10', stage:'Bruce Dickinscène', genre:'Black Metal',        country:'🇫🇷 France',    desc:'Black metal atmosphérique français aux influences nordiques. Hrafngrimr tisse une toile de riffs gelés et d\'atmosphères hivernales.' },
        { id:'2026-fri-27', name:'Miracle of Sound',             time:'19:10', end:'20:00', stage:'Bruce Dickinscène', genre:'Rock/Metal',         country:'🇮🇪 Irlande',   desc:'Gavin Dunne alias Miracle of Sound — compositeur célèbre des réseaux pour ses tributs musicaux aux jeux vidéo — s\'essaie à la scène.' },
        { id:'2026-fri-28', name:'VDouble o A',                  time:'21:00', end:'22:00', stage:'Bruce Dickinscène', genre:'Symphonic Metal',    country:'🇦🇹 Autriche',  desc:'Metal symphonique maritime et épique d\'Autriche. Visions of Atlantis emmènent vers des horizons nautiques avec deux chanteurs et une orchestration somptueuse.' },
        { id:'2026-fri-29', name:'Master Boot Record',           time:'23:00', end:'00:10', stroke:'Bruce Dickinscène', genre:'Chiptune/Metal',     country:'🇮🇹 Italie',    desc:'Projet unique mélangeant chiptune 8-bit et metal. Master Boot Record transforme des sons de Game Boy en symphonies métalliques absurdes et brillantes.' },
        { id:'2026-fri-30', name:'Eihwar',                       time:'01:20', end:'02:20', stage:'Bruce Dickinscène', genre:'Folk/Black',         country:'🇫🇷 France',    desc:'Black metal folk normand aux thèmes nordiques et aux accents celtiques. Eihwar forgent un metal du terroir profondément ancré.' }
      ],
      saturday: [
        { id:'2026-sat-01', name:'Necrowretch',          time:'12:45', end:'13:25', stage:'Dave Mustage',      genre:'Black/Death',       country:'🇫🇷 France',    desc:'Black death metal français cru et primitif. Necrowretch honorent l\'underground de la manière la plus directe qui soit.' },
        { id:'2026-sat-02', name:'Ashen',                time:'14:15', end:'14:55', stage:'Dave Mustage',      genre:'Post-Black',        country:'🇺🇸 USA',       desc:'Post-black metal américain atmosphérique et mélodique. Ashen créent des ambiances immersives entre mélancolie et intensité.' },
        { id:'2026-sat-03', name:'Ill Niño',             time:'15:45', end:'16:30', stage:'Dave Mustage',      genre:'Nu-Metal/Groove',   country:'🇺🇸 USA',       desc:'Nu-metal groove latino de New York. Ill Niño mêlent percussion latine et metal lourd dans un mélange qui fait encore mouvoir les foules.' },
        { id:'2026-sat-04', name:'Orden Ogan',           time:'17:25', end:'18:10', stage:'Dave Mustage',      genre:'Power Metal',       country:'🇩🇪 Allemagne', desc:'Power metal épique allemand aux hymnes galvanisants. Orden Ogan combinent productivité et qualité dans un metal grandiloquent et assumé.' },
        { id:'2026-sat-05', name:'Leprous',              time:'19:10', end:'20:00', stage:'Dave Mustage',      genre:'Prog Metal',        country:'🇳🇴 Norvège',   desc:'Metal progressif norvégien d\'une originalité et d\'une sophistication remarquables. Leprous repoussent les frontières du genre avec chaque album.' },
        { id:'2026-sat-06', name:'Eisbrecher',           time:'21:00', end:'22:00', stage:'Dave Mustage',      genre:'Industrial Metal',  country:'🇩🇪 Allemagne', desc:'Industrial metal allemand entre Rammstein et Die Krupps. Eisbrecher font danser les headbangers avec leurs synthés massifs et leurs riffs lourds.' },
        { id:'2026-sat-07', name:'Within Temptation',    time:'23:00', end:'00:10', stage:'Dave Mustage',      genre:'Symphonic Metal',   country:'🇳🇱 Pays-Bas',  desc:'Géants du metal symphonique néerlandais. Sharon den Adel et Within Temptation offrent une production scénique grandiose et des hymnes universels.' },
        { id:'2026-sat-08', name:'Perturbator',          time:'01:30', end:'02:30', stage:'Dave Mustage',      genre:'Synthwave/Metal',   country:'🇫🇷 France',    desc:'James Kent alias Perturbator fusionne synthwave rétro-futuriste et metal industriel dans des sets nocturnes hypnotiques et fascinants.' },
        { id:'2026-sat-09', name:'Aorlhac',              time:'13:30', end:'14:10', stage:'Supositor Stage',   genre:'Black Metal',       country:'🇫🇷 France',    desc:'Black metal atmosphérique français aux textes occitans et à l\'identité régionale affirmée. Aorlhac portent leur terroir dans leur musique.' },
        { id:'2026-sat-10', name:'Rectal Smegma',        time:'15:00', end:'15:40', stage:'Supositor Stage',   genre:'Noise/Grind',       country:'🇳🇱 Pays-Bas',  desc:'Noise grind néerlandais dans la grande tradition underground. Rectal Smegma incarnent l\'extrême pour l\'extrême, sans filtre ni explication.' },
        { id:'2026-sat-11', name:'Cancer',               time:'16:35', end:'17:20', stage:'Supositor Stage',   genre:'Death Metal',       country:'🇬🇧 UK',        desc:'Death metal britannique des origines depuis Worcester. Cancer reviennent avec leur son old-school massif et leur franchise musicale intacte.' },
        { id:'2026-sat-12', name:'Grave',                time:'18:15', end:'19:05', stage:'Supositor Stage',   genre:'Death Metal',       country:'🇸🇪 Suède',     desc:'Légendes du death metal suédois de Stockholm. Grave n\'ont jamais changé leur formule depuis 1986 et c\'est exactement ce qu\'on leur demande.' },
        { id:'2026-sat-13', name:'Anaal Nathrakh',       time:'20:05', end:'20:55', stage:'Supositor Stage',   genre:'Black/Grind',       country:'🇬🇧 UK',        desc:'Duo extrême britannique entre black metal industriel et grindcore apocalyptique. Anaal Nathrakh sont l\'un des groupes les plus intenses en live.' },
        { id:'2026-sat-14', name:'Nevermore',            time:'22:15', end:'23:05', stage:'Supositor Stage',   genre:'Progressive Thrash',country:'🇺🇸 USA',       desc:'Retour de Nevermore — metal progressif et thrash d\'une complexité fascinante, avec la voix inimitable de Warrel Dane en héritage.' },
        { id:'2026-sat-15', name:'Omnium Gatherum',      time:'00:25', end:'01:25', stage:'Supositor Stage',   genre:'Melodic Death',     country:'🇫🇮 Finlande',  desc:'Melodic death metal finlandais de grande qualité. Omnium Gatherum maîtrisent l\'art de la mélodie dans la brutalité depuis plus de 20 ans.' },
        { id:'2026-sat-16', name:'Basalt',               time:'13:30', end:'14:10', stage:'Massey Ferguscène', genre:'Sludge/Post-Metal', country:'🇧🇪 Belgique',  desc:'Sludge post-metal belge massif et minimaliste. Basalt imposent leur lourdeur avec une économie de moyens redoutablement efficace.' },
        { id:'2026-sat-17', name:'Bruit≤',               time:'15:00', end:'15:40', stage:'Massey Ferguscène', genre:'Post-Rock/Metal',   country:'🇫🇷 France',    desc:'Post-rock et metal instrumental français aux compositions épiques. Bruit≤ construisent des architectures sonores d\'une beauté mélancolique.' },
        { id:'2026-sat-18', name:'Hollow Jan',           time:'16:35', end:'17:20', stage:'Massey Ferguscène', genre:'Metal/Electro',     country:'🇫🇷 France',    desc:'Projet metal électronique français entre industriel et ambiant. Hollow Jan construit des mondes sonores intrigants et enveloppants.' },
        { id:'2026-sat-19', name:'Múr',                  time:'18:15', end:'19:05', stage:'Massey Ferguscène', genre:'Sludge/Post-Metal', country:'🇫🇷 France',    desc:'Sludge et post-metal français aux compositions lentes et massives. Múr imposent leur lourdeur avec patience et conviction.' },
        { id:'2026-sat-20', name:'Slift',                time:'20:05', end:'20:55', stage:'Massey Ferguscène', genre:'Psych/Stoner',      country:'🇫🇷 France',    desc:'Space rock et stoner psychédélique toulousain d\'une puissance cosmique. Slift sont l\'un des groupes les plus excitants de la scène rock française actuelle.' },
        { id:'2026-sat-21', name:'Svinkels Friends & Fam',time:'22:15',end:'23:05', stage:'Massey Ferguscène', genre:'Hip-Hop/Metal', color:'🇫🇷 France',   desc:'Le collectif hip-hop punk français Svinkels et ses invités — une fête chaotique et survoltée à mi-chemin entre rap et punk rock.' },
        { id:'2026-sat-22', name:'Sierra Veins',         time:'00:25', end:'01:25', stage:'Massey Ferguscène', genre:'Post-Metal',        country:'🇬🇧 UK',        desc:'Post-metal atmosphérique britannique aux textures sombres and aux compositions longues. Sierra Veins créent des paysages musicaux enveloppants.' },
        { id:'2026-sat-23', name:'Shady Fat Katz',       time:'12:45', end:'13:25', stage:'Bruce Dickinscène', genre:'Groove/Stoner',     country:'🇺🇸 USA',       desc:'Groove stoner américain aux influences hip-hop et metal. Shady Fat Katz balancent un son groovy et détendu qui fait bouger tout le monde.' },
        { id:'2026-sat-24', name:'Monde de Merde',       time:'14:15', end:'14:55', stage:'Bruce Dickinscène', genre:'Hardcore/Punk',     country:'🇫🇷 France',    desc:'Hardcore punk français direct et engagé. Monde de Merde décrit le monde avec la rage et la franchise d\'un groupe qui n\'en peut plus.' },
        { id:'2026-sat-25', name:'Jetsex',               time:'15:45', end:'16:30', stage:'Bruce Dickinscène', genre:'Rock/Metal',        country:'🇫🇷 France',    desc:'Rock metal français avec une touche provocatrice. Jetsex imposent leur personnalité forte dans un univers entre glam rock et metal moderne.' },
        { id:'2026-sat-26', name:'The Casualties',       time:'17:25', end:'18:10', stage:'Bruce Dickinscène', genre:'Street Punk',       country:'🇺🇸 USA',       desc:'Street punk new-yorkais depuis 1990. The Casualties enchaînent les concerts avec une loyauté absolue envers leur public et leur son brut.' },
        { id:'2026-sat-27', name:'Les 3 Fromages',       time:'19:10', end:'20:00', stage:'Bruce Dickinscène', genre:'Comedy/Metal',      country:'🇫🇷 France',    desc:'Le projet metal comique français par excellence. Les 3 Fromages mélangent metal, humour et fromage dans un spectacle qui détend l\'atmosphère.' },
        { id:'2026-sat-28', name:'Frog Leap',            time:'21:00', end:'22:00', stage:'Bruce Dickinscène', genre:'Acoustic Metal',    country:'🇳🇴 Norvège',   desc:'Leo Moracchioli aka Frog Leap, star YouTube des reprises metal acoustiques. Ce qu\'il fait sur écran, il le fait sur scène avec autant de talent.' },
        { id:'2026-sat-29', name:'Steven\'n\'Seagulls',  time:'23:10', end:'00:20', stage:'Bruce Dickinscène', genre:'Bluegrass Metal',   country:'🇫🇮 Finlande',  desc:'Finlandais déjantés qui reprennent des classiques du metal en version bluegrass acoustique. Jouissif, virtuose et complètement improbable.' },
        { id:'2026-sat-30', name:'Nanowar of Steel',     time:'01:30', end:'02:30', stage:'Bruce Dickinscène', genre:'Comedy Metal',      country:'🇮🇹 Italie',    desc:'Power metal parodique et hilarant d\'Italie. Nanowar of Steel parodient tous les clichés du metal avec un talent musical réel et un humour décapant.' }
      ],
      sunday: [
        { id:'2026-sun-01', name:'Holy Mother',          time:'11:45', end:'12:25', stage:'Dave Mustage',      genre:'Heavy Metal',        country:'🇺🇸 USA',       desc:'Heavy metal américain traditionnel aux hymnes puissants. Holy Mother cultivent un son classique et intemporel avec conviction.' },
        { id:'2026-sun-02', name:'Jools',                time:'13:05', end:'13:45', stage:'Dave Mustage',      genre:'Metal/Alt',          country:'🇫🇷 France',    desc:'Artiste metal alternatif français à la personnalité affirmée. Jools apporte sa vision singulière du metal avec une énergie scénique communicative.' },
        { id:'sun-03', name:'Killers',              time:'14:30', end:'15:10', stage:'Dave Mustage',      genre:'Heavy Metal',        country:'🇫🇷 France',    desc:'Institution du heavy metal français fondée par des membres d\'Iron Maiden. Killers portent depuis 40 ans un metal puissant et sincère.' },
        { id:'2026-sun-04', name:'Fit for an Autopsy',   time:'16:05', end:'16:50', stage:'Dave Mustage',      genre:'Deathcore',          country:'🇺🇸 USA',       desc:'Deathcore américain de haute qualité avec une touche technique et atmosphérique. Fit for an Autopsy sont devenus un acteur majeur du metal extrême moderne.' },
        { id:'2026-sun-05', name:'Kim Dracula',          time:'17:50', end:'18:40', stage:'Dave Mustage',      genre:'Alt/Nu-Metal',       country:'🇦🇺 Australie', desc:'Artiste alt-metal et nu-metal australien au style visuel extravagant. Kim Dracula mélange esthétique glam horror et metal percutant.' },
        { id:'2026-sun-06', name:'Airbourne',            time:'19:40', end:'20:40', stage:'Dave Mustage',      genre:'Hard Rock',          country:'🇦🇺 Australie', desc:'Hard rock australien survitaminé. Airbourne sont les héritiers spirituels d\'AC/DC, avec autant d\'énergie brute et de riffs entraînants.' },
        { id:'2026-sun-07', name:'Judas Priest',         time:'21:40', end:'23:10', stage:'Dave Mustage',      genre:'Heavy Metal',        country:'🇬🇧 UK',        desc:'Têtes d\'affiche ultimes du dimanche. Judas Priest, les Metal Gods en personne. Rob Halford et ses acolytes pour une leçon d\'heavy metal depuis 1969.' },
        { id:'2026-sun-08', name:'Arch Enemy',           time:'00:10', end:'01:10', stage:'Dave Mustage',      genre:'Melodic Death',      country:'🇸🇪 Suède',     desc:'Melodic death metal suédois mené par la charismatique Alissa White-Gluz. Arch Enemy combinent technique guitaristique et présence scénique redoutable.' },
        { id:'2026-sun-09', name:'Internal Bleeding',    time:'12:25', end:'13:05', stage:'Supositor Stage',   genre:'Brutal Death',       country:'🇺🇸 USA',       desc:'Pionniers du brutal death metal de New York depuis 1991. Internal Bleeding sont l\'une des références absolues du genre, toujours en activité.' },
        { id:'2026-sun-10', name:'Heavy/Hitter',         time:'13:45', end:'14:25', stage:'Supositor Stage',   genre:'Hardcore/Metal',     country:'🇺🇸 USA',       desc:'Hardcore metal américain direct et frontal. Heavy/Hitter — le nom dit tout — assènent des coups sonores sans relâche.' },
        { id:'2026-sun-11', name:'Cryptopsy',            time:'15:15', end:'16:00', stage:'Supositor Stage',   genre:'Tech Death',         country:'🇨🇦 Canada',    desc:'Légende du death metal technique canadien avec le batteur Flo Mounier. Complexité clinique et brutalité chirurgicale pour connaisseurs.' },
        { id:'2026-sun-12', name:'Signs of the Swarm',   time:'16:55', end:'17:45', stage:'Supositor Stage',   genre:'Deathcore',          country:'🇺🇸 USA',       desc:'Deathcore américain brutal et précis. Signs of the Swarm imposent leur marque dans un style ultra-technique et physiquement dévastateur.' },
        { id:'2026-sun-13', name:'Witch Club Satan',      time:'18:45', end:'19:35', stage:'Supositor Stage',   genre:'Black/Rock',         country:'🇫🇷 France',    desc:'Black rock ésotérique français entre occultisme et rock\'n\'roll. Witch Club Satan cultivent une atmosphère rituelle avec un groove irrésistible.' },
        { id:'2026-sun-14', name:'Vader',                time:'20:45', end:'21:35', stage:'Supositor Stage',   genre:'Death Metal',        country:'🇵🇱 Pologne',   desc:'L\'institution du death metal polonais. Peter et Vader enchaînent les albums depuis 1983 avec une constance et une qualité exemplaires.' },
        { id:'2026-sun-15', name:'Sacred Reich',         time:'23:15', end:'00:05', stage:'Supositor Stage',   genre:'Thrash Metal',       country:'🇺🇸 USA',       desc:'Thrash metal d\'Arizona avec un message politique affirmé. Sacred Reich portent leur engagement depuis 1985 avec la même conviction.' },
        { id:'2026-sun-16', name:'Eyes',                 time:'12:25', end:'13:05', stage:'Massey Ferguscène', genre:'Metal/Punk',         country:'🇫🇷 France',    desc:'Metal punk français aux accents crust. Eyes sont l\'incarnation de la rage brute et de l\'authenticité punk dans un univers métal.' },
        { id:'2026-sun-17', name:'Heretoir',             time:'13:45', end:'14:25', stage:'Massey Ferguscène', genre:'Post-Black',         country:'🇩🇪 Allemagne', desc:'Post-black metal atmosphérique allemand entre mélancolie et violence. Heretoir construisent des ambiances immersives d\'une rare beauté sombre.' },
        { id:'2026-sun-18', name:'Pain Magazine',        time:'15:15', end:'16:00', stage:'Massey Ferguscène', genre:'Industrial/Rock',    country:'🇫🇷 France',    desc:'Rock industriel français entre Nine Inch Nails et metal alternatif. Pain Magazine construit des ambiances urbaines et dystopiques.' },
        { id:'2026-sun-19', name:'John Cxnnor',          time:'16:55', end:'17:45', stage:'Massey Ferguscène', genre:'Rap/Metal',          country:'🇫🇷 France',    desc:'Rappeur metal français au style hybride entre trap et metal. John Cxnnor explore des territoires sonores entre deux mondes.' },
        { id:'2026-sun-20', name:'Voivod',               time:'18:45', end:'19:35', stage:'Massey Ferguscène', genre:'Thrash/Prog',        country:'🇨🇦 Canada',    desc:'Légendes du thrash progressif québécois. Voivod ont inventé une science-fiction musicale unique depuis 1983 — inclassables et irremplaçables.' },
        { id:'2026-sun-21', name:'Deafheaven',           time:'20:45', end:'21:35', stage:'Massey Ferguscène', genre:'Post-Black/Shoegaze',country:'🇺🇸 USA',       desc:'Blackgaze californien qui a fait traverser le black metal au shoegaze. Deafheaven polarisent l\'underground mais leurs concerts sont des expériences totales.' },
        { id:'2026-sun-22', name:'Shaârghot',            time:'23:15', end:'00:05', stage:'Massey Ferguscène', genre:'Industrial Metal',   country:'🇫🇷 France',    desc:'Metal industriel français spectaculaire et théâtral. Les shows de Shaârghot sont des performances totales entre musique et art visuel.' },
        { id:'2026-sun-23', name:'Les Hommes Crabes',    time:'11:45', end:'12:25', stage:'Bruce Dickinscène', genre:'Rock/Metal',         country:'🇫🇷 France',    desc:'Groupe français à la personnalité décalée et à l\'humour assumé. Les Hommes Crabes apportent une touche d\'originalité bienvenue au programme.' },
        { id:'2026-sun-24', name:'Modder',               time:'13:05', end:'13:45', stage:'Bruce Dickinscène', genre:'Death/Black',        country:'🇫🇷 France',    desc:'Death black metal français à l\'esthétique sombre et aux compositions agressives. Modder incarnent l\'underground hexagonal avec conviction.' },
        { id:'2026-sun-25', name:'Red Sun Atacama',      time:'14:30', end:'15:10', stage:'Bruce Dickinscène', genre:'Stoner/Desert Rock', country:'🇫🇷 France',    desc:'Stoner et desert rock français aux riffs lourds et sableux. Red Sun Atacama évoquent les grandes étendues arides avec un son chaleureux et lourd.' },
        { id:'2026-sun-26', name:'Wormsand',             time:'16:05', end:'16:50', stage:'Bruce Dickinscène', genre:'Death/Doom',         country:'🇫🇷 France',    desc:'Death doom français aux ambiances sépulcrales et aux compositions lentes et oppressantes. Wormsand creusent profond dans l\'obscurité.' },
        { id:'2026-sun-27', name:'Castle Rat',           time:'17:50', end:'18:40', stage:'Bruce Dickinscène', genre:'Doom/Psych',         country:'🇺🇸 USA',       desc:'Doom psychédélique new-yorkais aux influences occultes et vintage. Castle Rat font revivre le son des années 70 dans une atmosphère envoûtante.' },
        { id:'2026-sun-28', name:'Monkeys on Mars',      time:'19:40', end:'20:40', stage:'Bruce Dickinscène', genre:'Space Rock/Metal',   country:'🇫🇷 France',    desc:'Space rock et metal cosmique français. Monkeys on Mars partent en orbite avec des riffs lourds et des synthés galactiques pour un voyage sonore.' },
        { id:'2026-sun-29', name:'Coltaine',             time:'21:40', end:'23:10', stage:'Bruce Dickinscène', genre:'Post-Metal',         country:'🇫🇷 France',    desc:'Post-metal français aux compositions atmosphériques et à la dynamique soigneusement construite. Coltaine savent alterner douceur et violence.' },
        { id:'2026-sun-30', name:'Warning',              time:'00:10', end:'01:10', stage:'Bruce Dickinscène', genre:'Epic Doom',          country:'🇬🇧 UK',        desc:'Doom metal épique britannique d\'une profondeur émotionnelle rare. Patrick Walker et Warning touchent à quelque chose d\'universel dans la lenteur.' }
      ]
    }
  },
  "2027": {
    dates: {
      thursday:  "2027-08-19",
      friday:    "2027-08-20",
      saturday:  "2027-08-21",
      sunday:    "2027-08-22"
    },
    stages: {
      "Dave Mustage":      { color: "#f97316", cls: "keltia" },
      "Supositor Stage":   { color: "#1a9e8f", cls: "dolmen" },
      "Massey Ferguscène": { color: "#7c4dff", cls: "menhir" },
      "Bruce Dickinscène": { color: "#22c55e", cls: "souterrain" }
    },
    lineup: {
      thursday: [
        { id:'2027-thu-01', name:'Groupe Test 2027', time:'17:00', end:'18:00', stage:'Dave Mustage', genre:'Heavy Metal', country:'🇫🇷 France', desc:'Premier groupe témoin pour l\'alignement de l\'édition 2027.' }
      ],
      friday: [],
      saturday: [],
      sunday: []
    }
  }
};

// Variables d'accès globales initialisées dynamiquement par l'application
let CURRENT_YEAR = localStorage.getItem('moto_year') || "2026";
let YEAR_DATA    = FESTIVAL_DATA[CURRENT_YEAR] || FESTIVAL_DATA["2026"];
let STAGES       = YEAR_DATA.stages;
let LINE_UP      = YEAR_DATA.lineup;
let DAY_DATES    = YEAR_DATA.dates;

function setGlobalYear(year) {
  if (!FESTIVAL_DATA[year]) return;
  CURRENT_YEAR = year;
  localStorage.setItem('moto_year', year);
  YEAR_DATA = FESTIVAL_DATA[year];
  STAGES    = YEAR_DATA.stages;
  LINE_UP   = YEAR_DATA.lineup;
  DAY_DATES = YEAR_DATA.dates;
}
